### ISSUE TITLE
让双链和链接的区分度更大一点

### ISSUE THREAD

**Issue by frostime** [TinkMingKing/siyuan-themes-vscodelite#3]
## issue

双链和普通的链接区别还是不够大，只能靠靠颜色的不同来区分，还是不够明显。

![image](https://github.com/TinkMingKing/siyuan-themes-vscodelite/assets/27268127/667f1ec2-f96a-4b52-b943-cd4cefb458a2)

### 参考别的主题

参考别的主题，很多都会在颜色之外用别的元素区分这两者。作者可以参考一下：

![image](https://github.com/TinkMingKing/siyuan-themes-vscodelite/assets/27268127/e62fafa3-6367-4762-bac2-593b819801c1)

![image](https://github.com/TinkMingKing/siyuan-themes-vscodelite/assets/27268127/b6289f29-3bd4-4aeb-a836-c50f47523644)

![image](https://github.com/TinkMingKing/siyuan-themes-vscodelite/assets/27268127/f70f4a2d-22d8-4029-932d-a03a3c31c6e0)

## solution

我个人比较推荐 dark+ light-blue 的做法，在双链前后加上标记。既然本主题采用了 vscode 风格来，那不妨也采用这种方案 ，这样既明显视觉上更加突出，也和整体的 UI 风格是一致的（markdown 标记风格吗）。

比如 light-blue 就是这种实现方案：

![image](https://github.com/TinkMingKing/siyuan-themes-vscodelite/assets/27268127/69e68f22-e757-418f-9170-5b967cc6362a)

**Comment by TinkMingKing** [comment]
试过各种样式，最后觉得不改最好，后续有好点的想法再去改改吧
