### ISSUE TITLE
不同层级的标签前面都是 `#` 是不是不太好？

### ISSUE THREAD

**Issue by frostime** [TinkMingKing/siyuan-themes-vscodelite#4]
考虑到 markdown 语法中几个 `#` 就表示几级的标题，我觉得在所有标题前面都放上一个 `#` 的这个设计可能会容易让人混淆。

![image](https://github.com/TinkMingKing/siyuan-themes-vscodelite/assets/27268127/9e8b53a6-5eed-495e-bc61-07bfcee98888)

这是我刚刚用这个主题最直观的感受，可能和作者的思路不太一样，这里反馈一下我的直观感受。

**Comment by TinkMingKing** [comment]
我觉得色彩区分很好，前面加个#为了美观，如果要多个#，排版不好看，说白了加色彩和#是为了标题层级间，标题和文段间区分开来，有考虑过pink主题那种，但是不想加icon，css样式像R主题那样的多个.的尾缀我感觉没必要，如果放到前面，又会有样式冲突，各种各样的问题，所以决定当前方案
