### ISSUE TITLE
[question]可以复刻代码自行调整主题吗

### ISSUE THREAD

**Issue by emptylight370** [TinkMingKing/siyuan-themes-vscodelite#7]
因为主题太久没有更新，所以想要自己动手调整主题样式，更符合自己的习惯（所以自然不方便提pr）。在这里想问一下复制代码自行调整有什么约束吗，对于发布到主题市场又有什么约束吗？
有什么明确的约束我可以留档自用，不对外发布的。
又以及，`scss`怎么实现的，是编辑文件夹里的`scss`文件，打包时将文件整合到一个文件里吗？还是直接编辑`theme.css`？

**Comment by TinkMingKing** [comment]
没有约束，如果是自用，自己改着用就行，scss相关，百度教程学习一下，想发布到主题市场的话参照官方说明

**Comment by emptylight370** [comment]
好的，谢谢
