### ISSUE TITLE
希望配置编辑能加入去除标题阴影开关

### ISSUE THREAD

**Issue by zed7th** [TinkMingKing/siyuan-themes-vscodelite#8]
RT，个人不太喜欢标题样式的阴影效果，但是又想保留彩色的标题样式，希望能加上开关可选标题阴影效果

**Comment by TinkMingKing** [comment]
这个已经不维护了，可以改用他人fork的版本进行反馈
https://github.com/lingfengyu-dreaming/siyuan-vscodelite-edit
